Personalized session
cuenca-mx/cuenca-python pull request #103
Opened 2021-01-06 22:30 UTC by ricardo8990

Agrega soporte para poder utilizar una sesión independiente de las credenciales por defecto

closes #100

2021-01-07 21:30 UTC, matin commented on cuenca/resources/base.py
> +from ..http import Session, session as default_session
rename `default_session` to `global_session`

2021-01-07 21:35 UTC, matin commented on cuenca/resources/base.py
> +    def refresh(self, session: Optional[Session] = None):
try this instead:
```python
def refresh(self, session: Session = global_session):
```

2021-01-08 01:55 UTC, matin requested changes
All methods that accept `session` as a kwarg should never accept it as a positional arg. There are still a couple cases that need to be changed. Otherwise, looks good!

2021-01-08 01:55 UTC, matin commented on cuenca/resources/cards.py
> +        session: Session = global_session,
Add `*` before this as well

2021-01-09 18:03 UTC, ricardo8990 commented on cuenca/resources/cards.py
> +        session: Session = global_session,
Done

2021-01-13 01:21 UTC, matin approved these changes

2021-01-13 01:21 UTC, merged

2021-01-13 01:21 UTC, matin commented
@ricardo8990 can you create the release?