New Resources - Endpoint and Webhook
cuenca-mx/cuenca-python pull request #215
Opened 2022-01-21 02:51 UTC by andreshndz

This is the first approach of `Endpoint` and `Webhook` resources.
There are classes that are not defined in this PR, but they will be defined in `cuenca-validations`.

Our goal is to use the resources like:

```python
import cuenca

# Endpoint
cuenca.Endpoint.create('https://yoururl.com')
cuenca.Endpoint.retrieve('id')
cuenca.Endpoint.update('id', is_active=False)
cuenca.Endpoint.deactivate('id')

# Webhook
cuenca.Webhook.retrieve('id')
cuenca.Webhook.all()  # This will retrieve all webhooks from his platform 
```

2022-02-28 18:17 UTC, alexviquez requested changes
Agrega un tes de cuando ya existe el endpoint, no te permita volver a crearlo si no solo actualizarlo

2022-02-28 18:17 UTC, alexviquez commented on tests/resources/test_endpoints.py
> +    assert not endpoint.deactivated_at
puedes agregar validación de que cambio el url a url.io

2022-02-28 18:17 UTC, alexviquez commented on tests/resources/test_webhooks.py
> +    assert webhook.event
puedes hacer un webhook all con más de un webhook en test porfa

2022-02-28 18:17 UTC, alexviquez commented on cuenca/resources/endpoints.py
> +        """
agrega más contexto

2022-03-05 01:24 UTC, andreshndz commented on cuenca/resources/endpoints.py
> +        resp = cls._update(endpoint_id, session=session, **req.dict())
Esto ya lo solucionamos con `is_active`

`deactivated_at` significa que fue eliminado
`is_active` sirve para que el cliente tenga el control de prenderlo y apagarlo cuando guste

2022-03-05 01:24 UTC, andreshndz commented on tests/resources/test_endpoints.py
> +    assert not endpoint.deactivated_at
Está en la línea 34

2022-03-05 01:43 UTC, andreshndz commented on cuenca/resources/endpoints.py
> +        return cast('Endpoint', cls._from_dict(resp))
Tengo problemas para usarlo porque posee un campo `deactivated_at` que no es opcional

2022-03-07 19:15 UTC, alexviquez requested changes
Lo de deactivable, y cuidar la info del cassete

2022-03-07 19:15 UTC, alexviquez commented on tests/resources/test_webhooks.py
> +    assert list(Webhook.all())
de un user nadamas, no todos, los cassetrs son gigantes y aparte tiene info de usuarios de stage con teléfonos

2022-03-07 19:15 UTC, alexviquez commented on cuenca/resources/endpoints.py
>          return cast('Endpoint', cls._from_dict(resp))
no comprendo porque no puedes usar Deactivable, para eso se diseño con la idea de no repetir código

2022-03-07 22:15 UTC, andreshndz commented on cuenca/resources/endpoints.py
>          return cast('Endpoint', cls._from_dict(resp))
Ya le investigué un poco más y es que `Deactivable` trae una propiedad llamada `is_active`, al igual que `Endpoint` tiene un atributo llamado `is_active`

Al correr los tests pasa este error:

```shell
FAILED tests/resources/test_endpoints.py::test_endpoint_retrieve - AttributeError: can't set attribute
FAILED tests/resources/test_endpoints.py::test_endpoint_create - AttributeError: can't set attribute
FAILED tests/resources/test_endpoints.py::test_endpoint_update - AttributeError: can't set attribute
FAILED tests/resources/test_endpoints.py::test_endpoint_deactivate - AttributeError: can't set attribute
```

2022-03-07 23:44 UTC, alexviquez requested changes
validations version

2022-03-07 23:44 UTC, alexviquez commented on requirements.txt
> +cuenca-validations==0.9.21.dev1
pon la versión

2022-03-07 23:54 UTC, rogelioLpz commented on cuenca/resources/endpoints.py
> +from cuenca.resources.base import (
Siempre usar rutas relativas

2022-03-08 00:04 UTC, rogelioLpz commented on cuenca/resources/endpoints.py
> +        :param is_active
`is_enable`

2022-03-08 00:07 UTC, rogelioLpz commented on tests/resources/test_endpoints.py
> +    assert not endpoint.deactivated_at
Si gustas puedes ponerlo como 
`assert enpoint.is_active`

2022-03-08 00:22 UTC, alexviquez approved these changes

2022-03-08 00:23 UTC, rogelioLpz approved these changes

2022-03-08 00:23 UTC, merged