Verifications 🛂
cuenca-mx/cuenca-python pull request #242
Opened 2022-03-16 16:48 UTC by andreshndz

New resource: Verifications

## How to use it?

Phone verifications:

```python
from cuenca import Verification

verification = Verification.create(
    sender='+525555555555', type=VerificationType.phone
)
Verification.verify(id=verification.id, code='111111')
```

Same way for Email verifications

```python
from cuenca import Verification

verification = Verification.create(
    sender='mail@cuenca.com', type=VerificationType.email
)
Verification.verify(id=verification.id, code='111111')
```

2022-03-16 18:28 UTC, rogelioLpz commented on cuenca/resources/verifications.py
> +)
Esto tambien se debería poder desde `cuenca_validations.types`no?

2022-03-16 18:32 UTC, rogelioLpz commented on cuenca/resources/verifications.py
> +        *,
Si no se esperan más argumentos no es necesario el *
Lo mismo en el otro metodo

2022-03-16 18:45 UTC, rogelioLpz commented on cuenca/version.py
> +__version__ = '0.7.18.dev3'
`0.8.0`

2022-03-16 18:51 UTC, rogelioLpz commented on setup.py
> -        'cuenca-validations>=0.9.18,<0.9.23',
Este si va.
`cuenca-validations>=0.10.0,<1.0.0`

2022-03-16 23:24 UTC, alexviquez commented on cuenca/resources/verifications.py
> +class Verification(Creatable, Retrievable, Updateable):
huy

2022-03-17 21:47 UTC, andreshndz commented on requirements.txt
> +cuenca-validations==0.9.24.dev1
Este queda en espera hasta que suban la nueva version de CV

2022-03-29 21:07 UTC, alexviquez requested changes
unos comments

2022-03-29 21:07 UTC, alexviquez commented on setup.py
> +        'cuenca-validations>=0.10.0,<1.0.0',
`'cuenca-validations>=0.10.0,<0.11.0'`

2022-03-29 21:07 UTC, alexviquez commented on tests/resources/test_verifications.py
> +    verification: Verification = Verification.verify(id='VE02', code='299566')
no es necesario type hint en este caso, quitar y poner ignore a mypy

2022-03-30 21:39 UTC, alexviquez submitted a review, later dismissed

2022-03-30 21:53 UTC, rogelioLpz approved these changes

2022-03-30 21:55 UTC, rogelioLpz commented
ya solo la descirpción del error pero ya lo veo bien

2022-03-30 22:01 UTC, alexviquez approved these changes

2022-03-30 22:02 UTC, merged