Making user queryable by identity_id
cuenca-mx/cuenca-python pull request #272
Opened 2022-06-06 22:48 UTC by agarrido19

This PR adds `identity_id` as query param for `User` resource

- closes #270
- related https://github.com/cuenca-mx/cuenca-validations/pull/247

2022-06-06 23:58 UTC, andreshndz requested changes
Solo dos cosas:
- Cambiar versión
- Test donde probemos un `User.all(identity=identity_id)`

Terminemos esto y se vaaaa

2022-06-06 23:58 UTC, andreshndz commented on requirements.txt
> +cuenca-validations==0.10.9.dev1
Recuerda cambiar la versión

2022-06-07 15:10 UTC, alexviquez requested changes

2022-06-07 15:10 UTC, alexviquez commented on tests/resources/test_users.py
> +    assert user == users[0]
esto esta mal, hacer uno y uno

2022-06-10 01:39 UTC, agarrido19 commented on tests/resources/test_users.py
> +    assert user == users[0]
Ya

2022-06-10 01:54 UTC, andreshndz requested changes
Solo el cambio de la version para subir

2022-06-10 01:54 UTC, andreshndz commented on requirements.txt
> +cuenca-validations==0.10.9.dev2
Version

2022-06-10 19:38 UTC, andreshndz approved these changes
Yo lo veo bien

2022-06-10 20:54 UTC, alexviquez requested changes
solo quitar espacios no necesarios y le damoh

2022-06-10 20:54 UTC, alexviquez commented on tests/resources/test_users.py
> +
quitar espacio 😡

2022-06-10 20:54 UTC, alexviquez commented on tests/resources/test_users.py
> +
espacio y vamonoh

2022-06-10 20:57 UTC, alexviquez approved these changes
chulo

2022-06-10 20:57 UTC, andreshndz approved these changes

2022-06-10 20:59 UTC, merged