Adding name to balance entries model
cuenca-mx/cuenca-python pull request #72
Opened 2020-10-12 23:36 UTC by agarrido19

Changes correspond to the counterpart in oaxaca PR: [cuenca-mx/oaxaca#166](https://github.com/cuenca-mx/oaxaca/pull/166)

2020-10-19 20:33 UTC, kerycdiaz commented on tests/resources/cassettes/test_balance_entry_related_transaction_not_exist.yaml
> +    uri: https://sandbox.cuenca.com/config/route_configuration.json
Los cassettes con esta url ya no son necesarios, eso solo se crean con el PR de ricardo, pero en el cuenca-python original no hace falta.

2020-10-19 20:57 UTC, kerycdiaz requested changes
Todo bien, solo ese comentario. Aunque tienen que hacer pruebas con un ledger_entry cn otro tipoo de transacción relacionada, ya que estooy casi seguro que dara error por un tema de oaxaca y el nombre que le da a las colecciones.

2020-10-19 22:07 UTC, alexviquez requested changes
Hay un type que no es necesario, e igual lo que dice keryc en los cassettes

2020-10-19 22:07 UTC, alexviquez commented on cuenca/resources/balance_entries.py
> +    type: EntryType
Este campo no es necesario, como dice el comentario el amount llega negativo en caso de un debit o credit, este type solo es necesario en oaxaca

2020-10-19 22:08 UTC, agarrido19 commented on cuenca/resources/balance_entries.py
> +    type: EntryType
Pero que no los modelos de `cuenca-python`  y de `Oaxaca` deben ser los mismos? para que no haya incosistencias

2020-10-19 22:10 UTC, alexviquez commented on cuenca/resources/balance_entries.py
> +    type: EntryType
Hay que buscar la forma de noo usar el type en oaxaca, para que no lo usemos aquí ya que es información irrelevante

2020-10-19 22:17 UTC, alexviquez commented on cuenca/resources/balance_entries.py
> +    type: EntryType
Analizando oaxaca creo que es mejoro dejar el type, así no tenemos que crear if else para este caso, es más fácil de leer también

2020-10-20 15:26 UTC, agarrido19 commented on tests/resources/cassettes/test_balance_entry_related_transaction_not_exist.yaml
> +    uri: https://sandbox.cuenca.com/config/route_configuration.json
Listo

2020-10-20 16:28 UTC, alexviquez submitted a review, later dismissed
Listo

2020-10-20 18:33 UTC, kerycdiaz approved these changes

2020-10-21 22:45 UTC, kerycdiaz approved these changes

2020-10-21 22:55 UTC, alexviquez commented
@agarrido19 Hay que actualizar el version.py

2020-10-21 23:01 UTC, alexviquez approved these changes

2020-10-21 23:01 UTC, merged